### ISSUE TITLE
Experiment with running Play with Docker on OpenShift

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#112]
A fun one...

To try out Play With Docker, try this:

* Go to https://labs.play-with-docker.com/ and sign in with your docker hub login
* Start
* Start an instance
* git clone https://github.com/swcurran/education
* cd education/LFS171x/indy-material/nodejs/
* ./manage build
* ./manage up
* Click on the "9000" link that shows up at the top.
* Destroy your instance

COOOOOOOLLLLLL!!!!

We think this could be very useful for Gov't people and those that can't run docker on their local machine.  With site above, you can't use credentials, but with a hosted instance, we could - people could edit code and then do "git push" to update their repo.  Cool stuff.

The platform is evidently just a docker instance, and the setup is in an open source repo - https://github.com/play-with-docker/play-with-docker.  Please take a brief look and determine if this could easily run on OpenShift.  Goes as far as you think is worthwhile - stop if it is too difficult or once you get a level of effort idea.

Todd and John are good with this.  If this can work - we can put it in it's own place in Pathfinder.

Thanks!

**Comment by WadeBarnes** [comment]
Had a very quick initial look.  This is very cool.

First hurdle to overcome would be access to the Docker deamon within OpenShift.  This is a protected resource within OpenShift.  Docker builder pods within OpenShift are actually granted privileged access and are closely guarded by OpenShift.  *I bumped against said sharp edges when trying to develop a generic process for building VON images.*

**Comment by swcurran** [comment]
Bummer, that sounds like a tough challenge. Ok... Hold off for now. If
anything comes to mind...

**Comment by WadeBarnes** [comment]
Yes it is a bummer.  This would be a cool tool for the Gov folks, as many of them are no even allowed to install things like Docker on their machines.
