### ISSUE TITLE
Develop a Docker Hub-hosted Indy-SDK/Node and VON image to use as a base for all projects

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#12]
Create an optimized image that can be used as the basis for all images that need access to HL-Indy (SDK and Node) and VON (Agent and X) capabilities.

A separate pipeline will be created to drive the build of the image and pushing to Docker Hub (or some other public repository).

The existing pipelines that require Indy/VON will be updated to use this image as the base.

**Comment by cywolf** [comment]
The base image is currently located at: https://github.com/PSPC-SPAC-buyandsell/von-image/tree/master/stable

There's a von-network build from it at: https://github.com/cywolf/von-network/tree/slim

OrgBook here, to be turned into a PR: https://github.com/cywolf/TheOrgBook/tree/von-image

For von-x it's simply the master branch. Currently all three build the image from GitHub, as it still needs to be added to Docker hub.
