### ISSUE TITLE
Update BCOvrin Digital Ocean Instances to use the new von-network ledger browser

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#121]
Andrew has updated the BCovrin Ledger Browser (e.g. http://159.89.115.24/) to load and make the ledger queryable.  Please update the BCovrin instances of von-network to use the server software.

Not a super high-priority, but it would be nice to have that in place.

Environments to Update:
- [x] BCovrin `dev` (http://159.89.115.24/)
- [x] BCovrin `test` (http://138.197.138.255/)
- [x] BCovrin `prod` (http://159.203.24.151/)

**Comment by WadeBarnes** [comment]
The BCovrin `dev` ledger has been reconfigured to use the standard Indy ports, and the associated proxy droplets have been decommissioned and deleted.

All ledgers other than the older `test` ledger (which is still supporting the older version of Permitify) have been upgraded to the latest version of `von-network`.
