### ISSUE TITLE
Implement DID-Auth for Services accessing TOB

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#13]
Use the approach from the @peacekeeper examples to implement DID-Auth between the VON-X services and TheOrgBook.  Within TOB use the Django administration capabilities to manage the authenticated users that represent the VON-X Services. 

Once implement, protect some of the TOB API endpoints using Django admin permissions associated with the Service authenticated users.

**Comment by cywolf** [comment]
Also present at https://github.com/cywolf/TheOrgBook/tree/von-image to be turned into a PR. Currently, enabling this would prevent Permitify from creating claims.
