### ISSUE TITLE
Upgrade VON-Image to VON Agent 1.0.0

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#17]
Upgrade VON-Image to VON Agent 1.0.0, creating a new tag for the image to enable upgrading various VON deployments to use the new Agent.

**Comment by WadeBarnes** [comment]
@cywolf, This appears to be done; tag `py35-indy1.3.1-dev-489-ew`.  Is that correct?

**Comment by WadeBarnes** [comment]
Actually that image still contains `von-agent==0.6.5`

**Comment by cywolf** [comment]
That image should be close, but I need to update TOB, von-x, and probably
von-network to see if everything is working properly. There’s some
significant API changes.

**Comment by WadeBarnes** [comment]
Sounds good.
