### ISSUE TITLE
Add search/filter options to the ledger browser; other clean ups

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#170]
Add the ability to filter the ledger browser for strings and by type of transaction (NYM, Schema, CredDef, RevReg, Accumulator).  If both are specified, AND the results.

Nice to have the pagination cleaned up so that we knew how many pages there were total and especially that we could jump to the beginning and end.  NOTE - there may have been a reset on the data that the UI didn't know about, as when I hit the end arrow, it took me to page 40, which didn't exist.

The current capability to show a specific transaction by number can be removed - I can't see the usefulness of that. Same with clicking on a transaction to fill in the number to search for and hiding the rest.  Not a particularly useful feature IMHO.

Super nice to have would be to be able to click on a string in a transaction and do a search based on that - the equivalent of `highlight`, `copy`, `click in search`, `paste`, `enter for search`.  However, that would require making every string a link which would probably be a bad idea.

The string search would be on any data in a transaction - if the string is in any part of the transaction (label, data), include it in the results. If not - exclude it.  I hope that is easy to do, and eliminates the need to turn this into a Solr exercise.

The text in the header "BC's Provisional Indy Network" should be replaced with the phrase from the front page.

![image.png](https://images.zenhubusercontent.com/594c511551aa2c3057829237/2314f128-02b3-4441-889d-d7ee492c4ceb)

**Comment by cywolf** [comment]
@swcurran Master has been updated with type and text filter options. At the moment the text filter only looks at transaction IDs, DIDs, aliases, and schema names.
