### ISSUE TITLE
BCCA Demo using Indy Cat Credential Registry

### ISSUE THREAD

**Issue by jljordan42** [bcgov/von#192]
Rough architecture for the BCCA Payment Hub demo environment![BCCA IndyCat Demo Architecture.jpg](https://images.zenhubusercontent.com/5849aef8b9dc3c6220233b11/e518d95d-71bd-4684-97fa-861812e61d99)

**Comment by swcurran** [comment]
@ianco - please add info that you worked on with Julian last week.  Thanks!

**Comment by jljordan42** [comment]
@ianco I think we can close this and point at BCCA repo you created.
