### ISSUE TITLE
Please setup a https://matomo.org/ server on OpenShift so that we can use it as a Google Analytics replacement

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#197]
Please install and setup a dev and, subsequently, a production deployment of https://matomo.org/ (formerly piwik) and provide information so that we can switch BC Orgbook tracking from Google Analytics to matomo.

Once completed, please activate the blocked task so that we can get our Google Analytics removed and start to use this.

**Comment by WadeBarnes** [comment]
Resources:
- https://matomo.org/docs/installation/
- https://matomo.org/pricing/
- https://github.com/matomo-org/matomo
- https://hub.docker.com/_/matomo
  - Image runs a Matomo service only (in the form of FastCGI).  Requires MySQL and Nginx (web server/proxy) containers to support the micro service architecture.
- https://hub.docker.com/r/bitnami/matomo

**Comment by esune** [comment]
I set-up a Fathom instance in OpenShift, now updating ToB to use it instead of Google Analytics to see what data it comes up with.

**Comment by esune** [comment]
Both Fathom and Matomo are up and running, and the tracking code has been added to ToB and Vonx.io

**Comment by WadeBarnes** [comment]
[fathom-openshift](https://github.com/BCDevOps/fathom-openshift) project contributed to BCDevOps

**Comment by WadeBarnes** [comment]
[matomo-openshift](https://github.com/BCDevOps/matomo-openshift) project contributed to BCDevOps.
