### ISSUE TITLE
Vulnerability to address - bootstrap 4.3.1 - dFlow, TheOrgBook and probably IndyCat CR

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#208]
Per GitHub - 

> We found a potential security vulnerability in a repository for which you have been granted security alert access.
> 
> @bcgov                             	bcgov/dFlow
> Known moderate severity security vulnerability detected in bootstrap >= 4.0.0, < 4.3.1 defined in package-lock.json.
> package-lock.json update suggested: bootstrap ~> 4.3.1.
> Always verify the validity and compatibility of suggestions with your codebase.

If necessary, talk to Andrew about this.  Hopefully, it's just a minor update.

**Comment by esune** [comment]
* [this PR](https://github.com/bcgov/dFlow/pull/214) addresses the changes in dFlow
* [this PR](https://github.com/bcgov/TheOrgBook/pull/767) addresses the changes in ToB
* [this PR](https://github.com/bcgov/indy-catalyst/pull/93) addresses the changes in IndyCat CR
