### ISSUE TITLE
Define a simple backup strategy for the VON/Any Ghost-based Blog site.

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#21]
It's probably sufficient to just make periodic (e.g. daily) backups so that we have a way to survive corruption of the database. Retain some number (30?) copies of the backup to gluster storage after confirming that the gluster storage is treated by ESIT as backed up based on Tier 2 rules...e.g. incremental, daily, weekly and monthly backups.

Worst case if ESIT is not backing up data (which we really need to know...) - come up with a way to periodically export database to some other place outside of OpenShift.

**Comment by swcurran** [comment]
From @WadeBarnes:

Our ghost instance is attached to CNS storage; therefore not backed up at all.

There is a bit of a disconnect in what ESIT is backing up at the moment.

Legacy PVCs are being backed up daily and retained for 90 days.

The new CNS PVCs that we've all been encouraged to migrate toward are NOT being backed up at all at the moment. I've inquired as to when this is expected to occur.

The short answer is that they are considering leaving the backups to the project teams.

This raises some questions:
- What is the recommended backup strategy?
- Where do we put our backups?
- Is the backup location safe/secure (backed up)?

Angelika is going to look into the questions for us. The output may be a backup policy statement and some recommendations for the project teams.

**Comment by WadeBarnes** [comment]
The recommend approach at the moment is to provision some non-CNS storage and backup the files to there.  The non-CNS storage is backed up behind the scenes.
