### ISSUE TITLE
Interoperable Hyperledger Indy Mobile Agent Capabilities

### ISSUE THREAD

**Issue by bcdevex** [bcgov/von#213]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-interoperable-hyperledger-indy-mobile-agent-capabilities"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-interoperable-hyperledger-indy-mobile-agent-capabilities">visit the opportunity page</a>.
The opportunity closes on <b>Monday, April 1st, 2019 at 16:00 PDT</b>.</p>

**Comment by jakubkoci** [comment]
Is it possible to implement it in React Native?

**Comment by swcurran** [comment]
Yes, React Native implementations would be fine.

We have some ideas on the UX/UI design, and would expect a reasonable period of collaborative iteration on the UX/UI for the deliverable.

**Comment by mark-a-wilson** [comment]
If anyone is perplexed about how to upload an attachment to their proposal:
You need to "Save Changes" in your proposal first. This establishes your proposal as a draft, and then you can go back in and you should see an Attachments tab.
(Apologies for this UX ... improvement to come!) 🤷‍♂️

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by jljordan42** [comment]
Thanks to the three proponents for their proposal submissions. After evaluation we have assigned this CWU opportunity to @bcdevex @tmarkovski 

Again thanks and if there are any questions then please feel free to contact me.

**Comment by brianorwhatever** [comment]
congratulations @tmarkovski!

**Comment by swcurran** [comment]
A final wrap up on this now completed Code With Us Opportunity.  The project went extremely well, concluding with an excellent demo presented at the IIW 28 (https://internetidentityworkshop.com/) in Mountain View, CA on April 30-May 2 and continuing to be used. The demo overview can be found here - give it a try!  The BC Gov team built the Agent services referenced in the overview (Email Verification Service and IIWBook), while @tmarkovski completed a number of updates to his Streetcred IOS mobile agent app to ensure interoperability with the Agent services, extending its support of several DIDComm protocol and improvements to the mobile user experience.

Link to IIW session: https://iiw.idcommons.net/IIW_Book!_Come_get_a_REAL_IIW_attendance_verification_credential_and_prove_it_to_your_IIW_friends_using_your_phone!
Link to SSIMeetup.org about the IIWBook Demo: https://youtu.be/WfGXZaFajUU?t=954

The full set issues completed for the demo by all participants can be found here: https://github.com/bcgov/von/issues/214

The subset of IIW user experience demo issues completed by @tmarkovski can be found here: https://github.com/bcgov/von/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+streetcred

@tmarkovski also spent time during this CWU opportunity extending the Open Source agent-framework project (upon which Streetcred is built) to support additional DIDComm protocols. Details in that repo: https://github.com/streetcred-id/agent-framework

Awesome job! It was a pleasure working with @tmarkovski and presenting our work at IIW!
