### ISSUE TITLE
Streetcred: Remove/hide credentials when replacement credentials are received

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#230]
When someone gets a second credential that is the same type as an existing one, hide/remove the old one (as if it was revoked) and show only the new one.  This is likely fairly easy on the credentials screen.

Ideal if this was also handled in the "choose claims for presentation" user interface - only the most recent credential of the same type would appear.

NOTE: Over time this will need to get more capable.  We've dealt with this "reissue" process with OrgBook.  In the real world, a truly identical credential reissue would normally be handled as a "revoke" and "reissue".

**Comment by tmarkovski** [comment]
I added the ability to delete a credential from the listing screen. Would this satisfy this requirement for now or do you feel we should always override older credential?

**Comment by swcurran** [comment]
Yup - that works!  Thanks
On 4/20/2019 5:07:37 PM, Tomislav Markovski <notifications@github.com> wrote:
I added the ability to delete a credential from the listing screen. Would this satisfy this requirement for now or do you feel we should always override older credential?
