### ISSUE TITLE
Vulnerability in django

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#255]
Hey Nick,

Can you take a look at where we need to update this?  It's likely in multiple repos.  How do we make addressing these vulnerability updates routine? Should we have a mechanism that we upgrade all packages every time we do a commit and before we release?

We found a vulnerable dependency in a repository you have security alert access to.

@bcgov	bcgov/indy-email-verification

Known moderate severity security vulnerability detected in django >= 2.2.0, < 2.2.2 defined in requirements.txt.
requirements.txt update suggested: django ~> 2.2.2.

**Comment by nrempel** [comment]
@swcurran I can't seem to find any vulnerability notifications - https://github.com/bcgov/indy-email-verification/security/advisories

Maybe it's an external service that I don't have visibility into?

**Comment by WadeBarnes** [comment]
https://github.com/bcgov/indy-email-verification/network/alerts

**Comment by WadeBarnes** [comment]
Going to try the automated approach in GitHub.  I'll assign it for review when done.

**Comment by WadeBarnes** [comment]
Related PRs assigned directly;
- https://github.com/bcgov/indy-email-verification/pull/10
- https://github.com/bcgov/indy-email-verification/pull/11
