### ISSUE TITLE
Create a Red Hat Keycloak Identity Provider (IdP) capable of processing Verifiable Credentials using decentralized identity technology created by BC Gov to authorize access to a BC Government digital services

### ISSUE THREAD

**Issue by bcdevex** [bcgov/von#257]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-create-a-red-hat-keycloak-identity-provider--idp--capable-of-processing-verifiable-credentials-using-decentralized-identity-technology-created-by-bc-gov-to-authorize-access-to-a-bc-government-digital-service-"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-create-a-red-hat-keycloak-identity-provider--idp--capable-of-processing-verifiable-credentials-using-decentralized-identity-technology-created-by-bc-gov-to-authorize-access-to-a-bc-government-digital-service-">visit the opportunity page</a>.
The opportunity closes on <b>Wednesday, July 3rd, 2019 at 16:00 PDT</b>.</p>

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by jljordan42** [comment]
Thanks to the six proponents for their proposal submissions. After evaluation we have assigned this CWU opportunity to @bcdevex @tplooker

We really appreciate the effort folks went to. 

Again thanks and if there are any questions then please feel free to contact me.

**Comment by brianorwhatever** [comment]
Congratulations @tplooker!
