### ISSUE TITLE
Build IIW demo to demonstrate vc-authn-oidc using Keycloak to login using a credential

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#266]
The demo planned for IIW (October 1-3, 2019) demonstrates the use of a verifiable credential to login to a service using an OpenIDConnect (OIDC) interaction.  We want to effectively re-implement [this demo](https://www.youtube.com/watch?v=z_-j-2U06Bg), but with the addition of the Keycloak OIDC Provider that MattrGlobal is building.

Create a simulated government service that looks like the Access To Audio service (or another that we decide upon).  The UI should look like a service, but the only thing that should be dynamic about it is that it shows data from the verifiable credential that was presented to access the service.

Configure the service behind Keycloak, ideally with an option to use idir and github for authentication.  Deploy the service and the Keycloak realm.

On receipt of the code in [vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc) from MattrGlobal, configure and deploy that code and ACA-Py as an OIDC Provider (OP) parallel to IDIR and configure a proof request to be used by the OP. Configure a mapping of the claims returned by the OP to be passed in the OIDC token to the application, paralleling the data from idir and github.  Make sure that if the proof that is received does not reveal the values from the credential, access is denied.

It's not clear what mobile agent we can use for this.  If we can get a mobile agent that we can control and add to a different network, we'll use that, and we'll build a new credential issuing service that looks kind of (but not exactly) like it is the BC Law Society - http://lsbc.org.  On login to that fake service, the user should be able to enter information (First Name, Last Name) and be issued a verifiable credential.  That will then be used with the Keycloak OP.

If we don't get another mobile agent to use, we'll use the StreetCred mobile agent and at least the email verification service credential, and perhaps also the IIW demo credential.  If we use the IIW demo credential, we'll update the IIW service to remove the backend approval, making it a self-service interaction.  The Keycloak OP will then be configured to use one or both of those credentials.

**Comment by swcurran** [comment]
@jljordan42 @andrewwhitehead @nrempel @esune @WadeBarnes @tplooker - this is what I'm thinking will be the IIW Verifiable Credentials Authentication demo.

@WadeBarnes @esune - note the need to make a simulated MoJ site, and to deploy that site behind Keycloak with (initially) idir (if possible) and github authentication. Wade - thinking a static version of the A2A main screen, with just the name/email of the user dynamically displayed.  That build and deploy needs to go to a publically accessible site.

Feedback welcome - this is just a draft.  If you can see things that would make it easier, or other approaches let me know.

Note that we rely on the kindness of mobile agent makers for this.  We'll need to talk to them soon.

**Comment by esune** [comment]
Although his is technically complete, I am keeping the issue in review until the latest tweaks and fixes get in the repo.
