### ISSUE TITLE
Add Streetcred VC IdP to the Law Society Demo, updating as necessary so they can test

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#281]
Please add a new VC-based IdP to the Law Society Demo that matches (for now) the OSMA one, but that proves claims from the Verified Email credential.

As requested by Streetcred, adjust the proof request and message sent to their client. They want us to update the protocol family from 0.1 to 1.0.

**Comment by esune** [comment]
A new IDP has been added, however further changes are required to `vc-authn` to get the controller to build the correct presentation request.

**Comment by esune** [comment]
[This PR](https://github.com/bcgov/vc-authn-oidc/pull/18) tracks the changes to vc-authn. Code is ready to go, however I am still investigating a intermittent issue with base64 encoding of the resulting request JSON message.

**Comment by esune** [comment]
Code deployed, waiting for confirmation that everything works before merging and closing.
