### ISSUE TITLE
Add proof verification capability for the listed schema definition in IIW Book

### ISSUE THREAD

**Issue by seanadipose** [bcgov/von#284]
Please update the proof request in IIWBook to allow the schema to come from either the current email-verification credential or from the following credential.  Either should be accepted.

```
schema_definition {
  [
  'userdisplayname',
  'email',
  'surname',
  'givenname',
  'birthdate',
  'streetaddress',
  'locality',
  'stateorprovince',
  'postalcode',
  'country',
  'time'

  ],
  schema_name: 'verified_person',
  schema_version: '1.0'
};
```

**Comment by swcurran** [comment]
@nrempel - is this doable?  Let me know how hard this is.

Thanks!

**Comment by nrempel** [comment]
This can be done by changing the proof request restrictions here: https://github.com/bcgov/iiwbook/blob/master/src/iiw_book/views.py#L208

Currently we are just using a restriction on the schema name as well as the issuer's DID which we need ahead of time. Once the issuer has a did registered we can use that.

Question: should we accept either at any time or different schemas in different scenarios?

**Comment by swcurran** [comment]
Any at any time.

**Comment by nrempel** [comment]
Great, I'll get the DID from Emiliano tomorrow and add the exception

**Comment by swcurran** [comment]
This is complete.
