### ISSUE TITLE
Create a demo repo of web framework(s) using OIDC libraries and vc-authn-oidc for authentication 

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#288]
While our initial use case for the [vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc) was as an IdP to use with Keycloak (or other IAMs), the component should work when invoked directly from a web framework (such as Django) using an OIDC library (such as https://libraries.io/pypi/django-oidc).

Test that theory out by implementing a reference web app that is configured to use a vc-authn-oidc instance based on the most popular OIDC library for the selected framework. Once working, document as a reference implementation the mechanism in a repo, including (ideally) a dockerized deployment.  At least investigate a second framework and if it is easy, create a second (and a third, and a fourth...) reference app to demonstrate the use with that framework.

Implement this with minimal changes to vc-authn-oidc (nothing that would break the primary use case) but consider if changes are needed for this use case. In particular, consider the changes that might be put in place if we wanted to offer multiple proof request types for different user types.  Do the OIDC libraries support using the same mechanism multiple times or would some change to the vc-authn-oidc component itself be needed?

**Comment by esune** [comment]
> consider the changes that might be put in place if we wanted to offer multiple proof request types for different user types. Do the OIDC libraries support using the same mechanism multiple times or would some change to the vc-authn-oidc component itself be needed?

@swcurran if I understand correctly, the way of achieving this is just by having several `Login as...` entries (multiple buttons, a dropdown+button combination, etc.) that will set the appropriate `pres_req_conf_id` to the query parameters passed to `vc-authn`, that will pick-up and use the configuration matching the provided id.

**Comment by swcurran** [comment]
That's what I'm thinking.  If you can easily set up "Login with Facebook" and "Login with Google", presumably you can have several "Login with VC1", "Login with VC2" that happen to point to the same service endpoint (URL) with different parameters.

**Comment by esune** [comment]
Also investigating packages listed here: https://djangopackages.org/grids/g/oidc/

**Comment by esune** [comment]
@swcurran the initial release of the demo app has been merged into the main repository.

Do we need this issue to track further work (e.g.: OpenShift deployment, other tech stach implementations) or should we close it and open new ones if necessary instead?

**Comment by swcurran** [comment]
I'd say close this one and open new ones as needed.
