### ISSUE TITLE
Getting OIDC vc-authn-oidc demo running on PWVon for the HGF (March 3-6)

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#303]
We want it running with good instructions to be used as part of the workshop.

**Comment by esune** [comment]
@swcurran PR opened with changes that allow to run the demo in PWV: https://github.com/bcgov/vc-authn-oidc/pull/45

There is a new readme file that lists the steps to run in PWV, not sure whether you want it to look more structured or we can just keep it as a "recipe" for this psecific case and the main demo readme can be considered...like a main readme.
