### ISSUE TITLE
Verify that AVCR runs on PWVon and has good instructions

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#304]

**Comment by ianco** [comment]
$ git clone https://github.com/bcgov/indy-catalyst.git
...
$ cd indy-catalyst/docker
[node1] (local) root@10.1.144.4 ~/indy-catalyst/docker
$ ./manage build
The s2i executable is needed and not on your path.
It can be downloaded from here: https://github.com/openshift/source-to-image/releases
Make sure you extract the binary and place it in a directory on your path.
[node1] (local) root@10.1.144.4 ~/indy-catalyst/docker
$

**Comment by ianco** [comment]
Error s2i is not available, I'll check how easy it is to add s2i to the PWD container

**Comment by ianco** [comment]
```
$ git clone https://github.com/ianco/s2i-releases.git
$ cd s2i-releases
$ tar xvf source-to-image-v1.2.0-2a579ecd-linux-386.tar
$ export PATH=~/s2i-releases:$PATH
```

... and then s2i is available ...

**Comment by ianco** [comment]
OK I am able to build & start:

- von-network
- indy-catalyst (aka AVCR)
- indy-catalyst-issuer-controller (test issuer, runs on mara)

EXCEPT that there is some weird issue starting the mara database, so I haven't yet been able to issue to AVCR in the PWV environment.
