### ISSUE TITLE
Deploy an ACA-Py agent container on OpenShift for Law Society to use

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#313]
Please spin up an instance of ACA-Py on OpenShift for Law Society to use.  Please make it a 0.4.0 version so that it works with Streetcred.  Please set an API Key and share it securely with Ian, so that he can share it with the LSBC team.

Thanks

**Comment by esune** [comment]
@ianco agent has been deployed, let me know if you need further OpenShift support or I can close this
