### ISSUE TITLE
Move indy-vdr from andrewwhitehead repo to bcgov and then to hyperledger

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#314]
Please make the transitions of the repos.

As you move to Hyperledger, try to avoid doing other than moving it directly, so there is an audit trail from bcgov to hyperledger. I'm not sure how that is done, but it would be nice to keep that clean.  In the past they have done other dancing that was odd to get that done.

**Comment by swcurran** [comment]
Pinging @WadeBarnes and @andrewwhitehead  on this.

**Comment by WadeBarnes** [comment]
@swcurran,
- Transferred to BCGov; https://github.com/bcgov/indy-vdr
- Added it to our GitHub feed.
- Added branch our standard branch protection including required DCO sign-off.

**Comment by swcurran** [comment]
@WadeBarnes - added to ZenHub. Can you work with Ry to get this moved to Indy in Hyperledger?

@jljordan42 - Please add confirmation to this issue that this contribution should be made by BC Gov.

**Comment by WadeBarnes** [comment]
Transfer complete
