### ISSUE TITLE
Verified Email site email send is very slow

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#322]
For some reason, it takes a long time between submitting your email address and getting the message from the service so that you can get your credential. Not sure why, but it is noticeable and it takes away from demo (and real) usage of the site.

Please investigate the send and see why it is taking so long.

Thanks

**Comment by esune** [comment]
I tried replicating the issue: logs do not show any error, and the email arrived in my inbox reasonably fast (within a minute I'd say).

**Comment by swcurran** [comment]
A minute is pretty slow -- especially in a demo.  It's weird - it used to be (as I recall) essentially instantaneous, and is for other services.

Despite the no errors, can you see how long it is spending in the app before it is sent?

**Comment by esune** [comment]
The app responded instantly to my request, I will try digging a bit more maybe with increased logging.

**Comment by esune** [comment]
I could not find anything weird, the app seems to be trying to send the email right away so I am not sure what could be going on.

The only thing I found was that we were not correctly clearing intervals once the credential is issued, this update should reduce the noise in the logs for new users coming to the issuing service.

See https://github.com/bcgov/indy-email-verification/pull/41
