### ISSUE TITLE
Migrate demo apps to Sovrin StagingNet

### ISSUE THREAD

**Issue by esune** [bcgov/von#341]
To promote interoperability and collaboration with the Hyperledger Indy community, we decide to migrate our demo applications from BCovrin Test to Sovrin StagingNet.

In general, registering the existing agents on StagingNet and switching them to point to the new ledger _should_ be enough.

**_Notes:_**
- We need to deploy a new instance of [vc-authn](https://github.com/bcgov/vc-authn-oidc) targeting Sovrin StagingNet. The existing instance will remain to support the apps still targeting BCovrin Test.
  - All the configurations in the deployed instance of `vc-authn` will need to be applied for the apps to be able to use the OIDC authentication against the service.
- Deployment configurations will need to be updated accordingly if any of the agent endpoints change.

## Plan of Attack

_`prod` environments and services will initially be registered with Sovrin StagingNet and will eventually be registered with Sovrin MainNet once the services transition to full production mode._

The `vc-authn-oidc` instances in the TrustOverIP environment(s) will be used to replace the single `vc-authn-oidc` instance in `devex-von-prod`.

Agent wallets can be reset, as all schemas and cred-defs will be reissued on the new ledger.  Existing Seeds and DIDs will be retained.

### Migrate exiting TrustOverIP services to Sovrin StagingNet
- [X] **Emiliano** - Register `vc-authn-oidc` instances with Sovrin StagingNet
  - [X] Dev
  - [X] Test
- [X] **Emiliano** - Register `issuer-a2a` instances with Sovrin StagingNet
  - [X] Dev
  - [X] Test
  - There is no `issuer-a2a` instance in `prod`.  These are meant for development and testing purposes only.

### Migrate the Essential Services Delivery Demo Apps to Sovrin StagingNet

Essential Services Delivery Demo instances will be configured to use the TrustOverIP `vc-authn-oidc` instances.
- ESD `dev` -> TrustOverIP `dev`
- ESD `test` -> TrustOverIP `test`
- ESD `prod` -> TrustOverIP `test`; since the ESD demo apps will never be registered on Sovrin MainNet, where the TrustOverIP `prod` environment will eventually be registered on Sovrin MainNet.

- [X] **Emiliano** - Register the services with the TrustOverIP `vc-authn-oidc` instances.
- [X] **Emiliano** - Update the authentication configurations for the issuers.
- [X] **Emiliano** - Update the `oidc-rp-provider-endpoint` setting for the visual verifier instances.
- [X] **Emiliano** - Deploy the updated authentication configurations for the issuers.
- [X] **Emiliano** - Deploy the `oidc-rp-provider-endpoint` settings updates for the visual verifier instances.
- [X] **Emiliano** - Register the agent instances with Sovrin StagingNet

- **bztwou-dev**
  - [X] agent-esr1
  - [X] issuer-web-esr1
  - [X] agent-esr2
  - [X] issuer-web-esr2
  - [X] agent-healthbc
  - [X] issuer-web-healthbc
  - [X] agent-medlab
  - [X] issuer-web-medlab
  - [X] agent-openvp
  - [X] issuer-web-openvp
  - [X] visual-verifier-safe-entry
  - [X] visual-verifier-safe-entry-c19

- **bztwou-test**
  - [X] agent-esr1
  - [X] issuer-web-esr1
  - [X] agent-esr2
  - [X] issuer-web-esr2
  - [X] agent-healthbc
  - [X] issuer-web-healthbc
  - [X] agent-medlab
  - [X] issuer-web-medlab
  - [X] agent-openvp
  - [X] issuer-web-openvp
  - [X] visual-verifier-safe-entry
  - [X] visual-verifier-safe-entry-c19

- **bztwou-prod**
  - [X] agent-esr1
  - [X] issuer-web-esr1
  - [X] agent-esr2
  - [X] issuer-web-esr2
  - [X] agent-healthbc
  - [X] issuer-web-healthbc
  - [X] agent-medlab
  - [X] issuer-web-medlab
  - [X] agent-openvp
  - [X] issuer-web-openvp
  - [X] visual-verifier-safe-entry
  - [X] visual-verifier-safe-entry-c19

### Migrate the Identity Kit Demo Agents to Sovrin StagingNet

Identity Kit Demo Agents instances will be configured to use the TrustOverIP `vc-authn-oidc` instances.
- IDK `devex-von-test` -> TrustOverIP `test`
- IDK `devex-von-prod` -> TrustOverIP `test`; since the IDK demos will never be registered on Sovrin MainNet, where the TrustOverIP `prod` environment will eventually be registered on Sovrin MainNet.

- [X] **Emiliano** - Update the associated KeyCloak configurations to point to the TrustOverIP `vc-authn-oidc` instance.
- [X] **Emiliano** - Register the agent instances with Sovrin StagingNet

- **devex-von-test**
  - [X] identity-kit-agent-bc

- **devex-von-prod**
  - [X] identity-kit-agent-bc

### Migrate the Email Verification Service and ConfBook Demo Apps to Sovrin StagingNet

- [X] **Emiliano** - Register the agent instances with Sovrin StagingNet

- devex-von-image-tools
  - [X] email-verification-agent
  - [X] iiw-book-agent

**Comment by swcurran** [comment]
In addition to the technical updates, a number of documents in a variety of repos will need to be updated to change the references from `test.bcovrin...` to something appropriate for the new ledger being used.

**Comment by WadeBarnes** [comment]
We have a full set of `vc-authn-oidc` instances (`dev`, `test`, `prod`) in the TrustOverIP environments.  Should we just migrate everything over to those?

**Comment by WadeBarnes** [comment]
@esune, Other than the dependency on a `vc-authn-oidc`, the Essential Services Delivery instances are self contained; correct?

**Comment by WadeBarnes** [comment]
Wallets will need to be reset

**Comment by WadeBarnes** [comment]
@esune, Where are we currently hosting instances of `vc-authn-oidc`, and what services are registered with each?

**Comment by esune** [comment]
@WadeBarnes as discussed in person, we only have one instance of `vc-authn-oidc` in `devex-von-prod`. The idea will be to switch to using the instances in the ToIP namespaces and get rid of the old one.

**Comment by esune** [comment]
A new [PR](https://github.com/bcgov/essential-services-delivery/pull/61) has been opened with the changes required by the issuer services in to use the new `vc-authn-controller` instances.

The settings for the `visual-verifier` instances have been updated as well: a redeploy is required for changes to be effective.

All the proof-configurations have been posted to the appropriate `vc-authn-controller` instances and so that they will be ready to go once the new issuer services are deployed.

_Assumptions made:_

- The issuer service URLs will remain unchanged
- The issuer service DIDs will remain unchanged

If any of the above is not true, additional tweaks will be required for the settings to match the environments and work correctly.

**Comment by WadeBarnes** [comment]
@esune, the above assumptions are correct.

**Comment by esune** [comment]
All services successfully migrated to StagingNet

**Comment by WadeBarnes** [comment]
All environments have been tested.
