### ISSUE TITLE
Law Society Revocation Support

### ISSUE THREAD

**Issue by esune** [bcgov/von#343]
We need to deploy a Tails Server for the Law Society issuer agent in order for revocation to be supported and them being able to develop this functionality.

1. [This PR](https://github.com/hyperledger/aries-cloudagent-python/pull) needs to be merged for the Tails Server to be released
2. We will likely want to update the current "quick-and-dirty" deployment configuration used for the development agent to be extended with Tails File support, and be ready for production. Current template is [here](https://github.com/bcgov/law-society-demo/tree/master/openshift/templates).

**Comment by swcurran** [comment]
Just to make sure this is clear.  We want a single tails server in BC Gov, not one per issuer. The tails server will be open for others to use as well.

I think that is what you intended, but wasn't certain.

**Comment by WadeBarnes** [comment]
The configurations for the tails server(s) were added to [bcgov/a2a-trust-over-ip-configurations](https://github.com/bcgov/a2a-trust-over-ip-configurations), which are the configurations for our TrustOverIP environments.

All tails-server instances have been deployed and tested:
- `https://tails-server-dev.pathfinder.gov.bc.ca`
- `https://tails-server-test.pathfinder.gov.bc.ca`
- `https://tails.vonx.io`
- `https://tails.orgbook.gov.bc.ca`

`https://tails.vonx.io` and `https://tails.orgbook.gov.bc.ca` point to the same `prod` server.

**Comment by WadeBarnes** [comment]
@esune, @swcurran, I think that addresses everything needed for this ticket.  Please review and confirm.

**Comment by esune** [comment]
@WadeBarnes looks good! Only missing thing is to connect the Law Society agent(s) to the appropriate ails servers once we move them over to the ToIP namespaces.
