### ISSUE TITLE
Revocation load testing

### ISSUE THREAD

**Issue by esune** [bcgov/von#357]

**Comment by esune** [comment]
@swcurran can I close this "generic" ticket I was using when load-testing revocation? Do we have new tickets, or do we need to log them?

c.c.: @sklump

**Comment by esune** [comment]
The issue I logged in [indy-sdk](https://github.com/hyperledger/indy-sdk/issues/2236) seems to have been acknowledged (thumbs up from one of the maintainers). Not sure whether we have additional things we need to track on our end.

**Comment by swcurran** [comment]
I think we should log a ticket in ACA-Py and document the risk there and track the indy-sdk solution there.  I also think we should add that to a README somewhere -- perhaps in the "dev" readme.

Are there any artifacts that will let us run a load test again in the future -- once the indy-sdk piece is completed?

**Comment by esune** [comment]
I logged a new issue to track the work: https://github.com/hyperledger/aries-cloudagent-python/issues/745

I created a small project that can help with load testing locally: all it does is spin up two agents using the same wallet, a controller, and start issuing/revoking credentials on a very small-sized registry. The code is [here](https://github.com/esune/revo-load-test).
