### ISSUE TITLE
Update VC Issuers/Verifiers with latest OIDC updates

### ISSUE THREAD

**Issue by amanji** [bcgov/von#382]
The following demo services should be updates to support the latest changes to `vc-authn-oidc` (adding support for connection-less presentation requests):

See [this](https://github.com/bcgov/vc-authn-oidc/pull/141) PR

* https://safeentrybc.vonx.io/
* https://openvp-issuer.apps.silver.devops.gov.bc.ca
* https://healthbc-issuer.apps.silver.devops.gov.bc.ca
* https://esr1-issuer.apps.silver.devops.gov.bc.ca
* https://esr2-issuer.apps.silver.devops.gov.bc.ca
* https://lngpipeline-camp.vonx.io/
* https://medlab-issuer.apps.silver.devops.gov.bc.ca
* https://long-term-care-facility.vonx.io/

**Comment by swcurran** [comment]
@wadeking98 -- can you start on this as a background task?  I'm hoping this is a relatively simple upgrade--not much labour and mostly just monitoring.  Likely you will want to discuss how to go about doing this with @WadeBarnes .

**Comment by amanji** [comment]
I believe the various services redirect to https://toip-vc-authn-controller-test.apps.silver.devops.gov.bc.ca for verification, so that should be the only service that needs to be updated.

**Comment by wadeking98** [comment]
okay dev and test have been updated.
