### ISSUE TITLE
VON-Anchor - Enable tagging credentials with a Credential ID

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#58]
Provide a capability (perhaps optional, perhaps automatic - your thoughts?) to generate a CredentialID for all credentials put into a wallet, tag the Credential with the ID and return the ID to the caller the ID of the newly stored credential.

**Comment by sklump** [comment]
* Every stored credential has always had a (wallet) identifier - it looks like a UUID, and VON Anchor `HolderProver.store_cred()` returns it as a string
* Tag creation per credential stored is automatic and immutable: schema_id, schema_issuer_did, schema_name, schema_version, issuer_did, cred_def_id, [attr::name::marker=1, attr::name::value for each attr as name:value, where value is understood to be raw (not encoded)]

**Comment by swcurran** [comment]
Marking this as done and cancelled:obe (overcome by events).  Just plain not needed.  Cool!
