### ISSUE TITLE
Figure out dependancies on Sovrin Provisional Ledger with respect to its upgrade from 1.3 to 1.5

### ISSUE THREAD

**Issue by jljordan42** [bcgov/von#69]

**Comment by swcurran** [comment]
The bottom line is that we need the Sovrin Nodes to support Indy-SDK 1.6 before we can use the Sovrin Provisional Network.  The challenge with using an earlier version of the Indy-SDK to create the Sovrin Node transactions we need is that the resulting Indy-SDK wallet will be of the old type (pre Indy-SDK 1.5) and there is not an upgrade for the wallet.  It's possible that we could try some trickier things - extract the text entries from the pre-Indy-SDK 1.6 wallet and write some code to store those in an Indy-SDK 1.6 wallet, but that seems pretty fragile. Only if really forced will we look into that.

So - the assumption currently is that we will wait for the Sovrin Provisional Network to be upgraded to be compatible with Indy-SDK 1.6 before we proceed.
