### ISSUE TITLE
Get access to DataBC API Gateway Management Interface

### ISSUE THREAD

**Issue by jljordan42** [bcgov/von#72]
Determine the steps necessary to register the TOB API with the DataBC API Gateway.

**Definition of TOB API:**
- **API** - in this context encompasses the endpoints required by a von-x based agent to register issuers and perform operations on credentials.  These endpoints are a subset of the API exposed by the tob-api and are grouped together in `/api/v2/indy/*`.  We absolutely do not want to expose the whole TOB API through the gateway.  To solve this, a path based route has been implemented to expose only the `/api/v2/indy/*` endpoints required by external agents.  _This route is being used by the BC Registries Agent implementations._

**Comment by jljordan42** [comment]
Info to register from DataBC Folks

To get started with the gateway we just need you to answer a couple of questions and create a metadata record in the BC Data Catalogue. We can also create a space for you in the api-specs repo to store the OpenAPI (3.x) spec for the OrgBook api that you could fork, add the spec, and send us a pull request. This spec will then be referenced by the metadata record and auto-generate an API console. If you need to secure the spec file (JSON) behind IDIR we also have a hosting option in BCDC.
 
In terms of next steps, to register your API with the gateway, select optional features, and to create a draft metadata record you can use a single form called the API Registration Generator (IDIR). The API Registration Generator can also be accessed by logging into BCDC and clicking on the ‘Register API’ button.
 
I can also provide any information on the features listed and call in Leo or Steve if need be as I’ll be on vacation tomorrow. That said, all of the information you type into the API Reg Generator is sent to Leo and Steve to finish the process.
 
Once the org book API is registered you will also be able to see the endpoint details using the Gateway admin app (IDIR).
 
 
Application links and user guides:
API Registration Generator: https://argg.apps.gov.bc.ca/int/
api-specs repo: https://github.com/bcgov/api-specs
BCDC: https://catalogue.data.gov.bc.ca/
Gateway Admin app (GWA): https://gwa.apps.gov.bc.ca/int/ui/endpoints
Guides:
API Registration
GWA (API owners)
GWA (developers)

https://www2.gov.bc.ca/gov/content/data/about-data-management/databc/databc-products-services/api-management

**Comment by WadeBarnes** [comment]
Registration with The DataBC API Gateway requests an OpenAPI (3.x) spec.  Our API incorporates the use of [django-rest-swagger](https://github.com/marcgibbons/django-rest-swagger/releases) which generates rich API documentation and OpenAPI specifications based on the source code.  The latest version appears to have added some additional support for newer specification versions.  The [documentation](https://django-rest-swagger.readthedocs.io/en/latest/) appears to be a little behind.  Another option used by the [gwells](https://github.com/bcgov/gwells) project, which is registered with the Gateway using an OpenAPI (3.x) spec, is [drf-yasg](https://github.com/axnsan12/drf-yasg) ([documentation](https://drf-yasg.readthedocs.io/en/stable/)).

At the moment our API documentation does not cover the `/api/v2/indy/*` endpoints that we want to publish.  The views for these endpoints may need to be updated to support the document generation process.  This is typically a fairly simple process.

**Comment by WadeBarnes** [comment]
The gwells spec can be found here; https://github.com/bcgov/api-specs/tree/master/gwells

**Comment by WadeBarnes** [comment]
The link to our OpenApi V3 spec can be found in this ticket; https://github.com/bcgov/TheOrgBook/issues/504

**Comment by WadeBarnes** [comment]
The latest version of the OpenAPI v3 spec can be found here; https://github.com/bcgov/TheOrgBook/tree/master/APISpec

It was updated last week and is already out of date.  It's fairly clear having to maintain this spec manually (export the latest v2 spec, convert it to v3, and hand-bomb the Indy endpoints in since they are not covered by the auto-generation) is not practical when the API and models are evolving from week to week.  We are also lacking a change management process at this point that lets us know the API or models have changed so we know to update the spec.

I think we should hold on publishing the API on the Gateway until we have something a bit more stable.
