### ISSUE TITLE
Add new EW to Dev instance based on Ian's snowflake implementation

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#86]
Ahead of the full integration of the EW into indy-sdk, please use the current implementation in the @ianco indy-sdk fork to deploy to official BC TOB Dev (or Test - your call) so that we can run an end-to-end test.

Assigning to Wade, support from Ian.

**Comment by WadeBarnes** [comment]
Related to https://github.com/bcgov/TheOrgBook/issues/470

**Comment by WadeBarnes** [comment]
Support for postgres wallet storage has been integrated into TheOrgBook and the BC TOB OpenShift configurations.  The configurations have been rolled out to the BC TOB `dev` and `test` environments for testing pending integration into any other environment.

Implementations are based on [von-image 1.6-ew](https://github.com/PSPC-SPAC-buyandsell/von-image/tree/master/1.6-ew).
