### ISSUE TITLE
VON Network - deploying to a non-local environment (e.g. Cloud Platform)

### ISSUE THREAD

**Issue by andrewBSTan** [bcgov/von#88]
While the steps here relates to how to run the network locally and access via localhost, may I know how can I deploy the network in a private network as I will have team members accessing the network from other machines.

Thanks.

**Comment by swcurran** [comment]
@nbrempel - can you please check the docs and write a brief summary on what we did for this for Digital Ocean?  Should be in the readme.

**Comment by andrewBSTan** [comment]
Appreciate the help here.  While I am able to run an instance of VON Network, TheOrgBook alongside with Permitify Service and able to access each of them outside of the local machine, I am struggling when say Permitify Service is trying to talk to TheOrgBook and VON Network which the Docker IP address cannot be resolve.
