### ISSUE TITLE
Add backups for postgres databases

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#92]
**Update - The plan is to migrate all components to postgres storage for wallets.  It makes backups easier, and solves a few other issues we've encountered with Sqlite wallets.**

Add a simple backup database approach for sqlite and postgres - eg a pod that sleeps, wakes up, runs a shell script to do a backup, goes back to sleep. 

If possible, get a Legacy PVC to provide additional backups.  Per Shea, you may be able to do that yourself, or worst, have to ask ESX (Steven B).  Need to do a compressed backup of a production DB to see how much space you are going to need.

Need to investigate best practices for a sqlite backup.

The initial investigation on backup strategies was done here; https://github.com/bcgov/von/issues/89.
This ticket will focus on implementation.

### Databases that need to be backed up:

**BC Registries Agent Environment**
- [x] Event Database - Postgres database on `event-db`
  - Current production size: 4.4 GB
- [x] Mara Database - Postgres database on `mara-db`; optional.  This database only contains processing logs which are not critical.
  - Current production size: 169 MB  
- [x] Agent Holder and Verifier Wallets - Sqlite databases on `bcreg-x-agent`
  - Current production size (together): 268 KB

**Ontario Registries Agent Environment**
- [x] Agent Holder and Verifier Wallets - Sqlite databases on `bcreg-x-agent`
  - Current production size (together): 268 KB

**TheOrgBook BC/Ont Environment**
- [x] Application/Search Database  - Postgres database on `postgresql`
  - Current production size: 9.3 GB
  - Compressed backup size: 839M
  - Required backup allocation: 35 GB
    - Based on rounding the compressed backup size to 1 GB, a rolling 31 days (one full month) of backups, plus a little headroom.
- [x] Holder and Verifier Wallets - Either, Sqlite databases on `django`, or  Postgres databases on `wallet-db`.  Note, the wallet databases used for the wallets are initially created by the application when the wallets are first registered and are separate from the 'main' database the pod is configured to create.  That database will be empty.
  - Current production size (Sqlite, together): 39 GB (The TheOrgBook_Verifier_Wallet is only 96 KB right now).

**_The TheOrgBook BC Environment also contains search and autocomplete indexes on the `solr` pod, however this data is not critical as it can easily and fairly quickly be recreated using the data from the Application/Search Database._**  Current production size: 1.3 GB (591 MB after rebuilding the indexes and autocomplete with the latest Solr schema version).

**Requirements based on production storage projections:**
TheOrgBook-BC Backup Storage
| Description          | Data (GB) | Compression | Backup (GB) | Num Backups | Required Size (GB) | 
|----------------------|-----------|-------------|-------------|-------------|--------------------| 
| Application database | 55        | 91%         | 5.0         | 10          | 50                 | 
| Wallet database      | 230       | 78%         | 51.0        | 10          | 510                | 
|                      |           |             |             | Total       | 560                | 

BC Registries Agent Backup Storage
| Description     | Data (GB) | Compression | Backup (GB) | Num Backups | Required Size (GB) | 
|-----------------|-----------|-------------|-------------|-------------|--------------------| 
| Event database  | 30        | 91%         | 2.7         | 10          | 27.09677419        | 
| Wallet database | 0.0003    | 78%         | 0.00007     | 10          | 0.000665854        | 
| Mara Database   | 0.2       | 91%         | 0.01806     | 10          | 0.180645161        | 
|                 |           |             |             | Total       | 27                 | 

TheOrgBook-Ont  Backup Storage
| Description          | Data (GB) | Compression | Backup (GB) | Num Backups | Required Size (GB) | 
|----------------------|-----------|-------------|-------------|-------------|--------------------| 
| Application database | 70        | 91%         | 6.3         | 10          | 63                 | 
| Wallet database      | 350       | 78%         | 77.7        | 10          | 777                | 
|                      |           |             |             | Total       | 840                | 

Ontario Registries Agent Backup Storage
| Description     | Data (GB) | Compression | Backup (GB) | Num Backups | Required Size (GB) | 
|-----------------|-----------|-------------|-------------|-------------|--------------------| 
| Wallet database | 0.0003    | 78%         | 0.00007     | 10          | 0.000665854        | 
|                 |           |             |             | Total       | 0.00067            | 

*Compression based on tests with actual data*

**Environments to update:**
- [x] devex-von-bc-registries-agent-tools - `build` configuration
- [x] devex-von-tools - `build` configuration
- [x] devex-von-bc-registries-agent-prod
- [x] devex-von-bc-tob-prod

- [x] ontvon-von-ont-registries-agent-tools - `build` configuration
- [x] ontvon-von-tools - `build` configuration
- [x] ontvon-von-ont-registries-agent-prod
- [x] ontvon-von-prod

**Comment by WadeBarnes** [comment]
https://github.com/bcgov/von/issues/89

**Comment by WadeBarnes** [comment]
For the Postgres backup strategy we're using the approach from the HETs Project which I've pulled out into it's own repository so it's easier enhance and maintain; https://github.com/BCDevOps/backup-container

**Initial Test Results:**
- Test build and deployment to production went smoothly.
- Tests run using gluster storage (because it's easier to provision dynamically) to get a feel for our storage requirements.
- The `dump` only takes about 15 minutes, and the resulting `gz` file is only 839M (the database is 9.3 GB w/ all supporting files and configuration).

Backup script output:
```
Making backup directory in /backups/2018-09-20/
Database backup written to /backups/2018-09-20/TheOrgBook_Database2018-09-20-14-26.sql.gz
Current Backups:
-rw-r--r--. 1 1002720000 2325 838M Sep 20 14:40 /backups//2018-09-20/TheOrgBook_Database2018-09-20-14-26.sql.gz
====================
```

Backup storage utilization:
```
sh-4.2$ du -ch /backups
838M    /backups/2018-09-20
839M    /backups
839M    total
sh-4.2$
1173897 201
```

Database utilization:
```
sh-4.2$ du -ch /var/lib/pgsql/data
4.0K    /var/lib/pgsql/data/.trashcan/internal_op
8.0K    /var/lib/pgsql/data/.trashcan
4.0K    /var/lib/pgsql/data/userdata/pg_xlog/archive_status
737M    /var/lib/pgsql/data/userdata/pg_xlog
468K    /var/lib/pgsql/data/userdata/global
668K    /var/lib/pgsql/data/userdata/pg_clog
4.0K    /var/lib/pgsql/data/userdata/pg_commit_ts
4.0K    /var/lib/pgsql/data/userdata/pg_dynshmem
12K     /var/lib/pgsql/data/userdata/pg_notify
4.0K    /var/lib/pgsql/data/userdata/pg_serial
4.0K    /var/lib/pgsql/data/userdata/pg_snapshots
28K     /var/lib/pgsql/data/userdata/pg_subtrans
4.0K    /var/lib/pgsql/data/userdata/pg_twophase
132K    /var/lib/pgsql/data/userdata/pg_multixact/members
60K     /var/lib/pgsql/data/userdata/pg_multixact/offsets
196K    /var/lib/pgsql/data/userdata/pg_multixact
6.8M    /var/lib/pgsql/data/userdata/base/1
6.8M    /var/lib/pgsql/data/userdata/base/12373
6.9M    /var/lib/pgsql/data/userdata/base/12378
8.5G    /var/lib/pgsql/data/userdata/base/16385
4.0K    /var/lib/pgsql/data/userdata/base/pgsql_tmp
8.5G    /var/lib/pgsql/data/userdata/base
4.0K    /var/lib/pgsql/data/userdata/pg_replslot
4.0K    /var/lib/pgsql/data/userdata/pg_tblspc
4.0K    /var/lib/pgsql/data/userdata/pg_stat
59K     /var/lib/pgsql/data/userdata/pg_stat_tmp
4.0K    /var/lib/pgsql/data/userdata/pg_logical/snapshots
4.0K    /var/lib/pgsql/data/userdata/pg_logical/mappings
12K     /var/lib/pgsql/data/userdata/pg_logical
1.8M    /var/lib/pgsql/data/userdata/pg_log
9.3G    /var/lib/pgsql/data/userdata
9.3G    /var/lib/pgsql/data
9.3G    total
```

**Comment by WadeBarnes** [comment]
The plan, now, is to migrate all components to postgres storage for wallets. It makes backups easier, and solves a few other issues we've encountered with Sqlite wallets

**Comment by WadeBarnes** [comment]
We're migrating everything over to postgres wallet storage, so we don't need the Sqlite backups anymore.

**Comment by WadeBarnes** [comment]
Added and tested support for backing up multiple Postgres databases within an environment.

Remaining:
- Pruning strategy for keeping a week's worth of daily backups, plus the previous 3/4 weekly backups.
- Update the deployment configurations to mount the list of databases to be backed up.
- Deploy to the prod environments.

**Comment by WadeBarnes** [comment]
Good progress made over the last couple days.  I've finished extending the [backup-container](https://github.com/BCDevOps/backup-container) project to support backing up multiple databases and to support a rolling backup strategy.  Build and deployment configurations for `bc-tob` and `ontario` TOB profiles have been created.  Thorough testing has been going on in the `bc-tob` `test` environment and locally for the last couple days.  A few things to wrap up on the TOB side before the changes can be PRed.  Then on to integrating the backups into the BC Registries and Ontario Registries Agents.  That will go faster because all of the heavy lifting and testing has been done.

Still waiting on the backup storage to be allocated.

**Comment by WadeBarnes** [comment]
The backup configurations are complete.  The build configurations have been deployed to all of the environments.

Just waiting on for the storage to be allocated before pushing the deployment configurations into the environments.

**Comment by WadeBarnes** [comment]
I've configured backups on the BC production environments using temporary storage while we're waiting for the manual storage to be allocated.

**Comment by WadeBarnes** [comment]
I received the manual classed storage for the backups on all by the `devex-von-bc-registries-agent-prod` environment.  Backups have been deployed into all environments.  `devex-von-bc-registries-agent-prod` is running on temporary storage for the moment.

**Comment by WadeBarnes** [comment]
All permanent backup storage is in place.
